version: "3"

services:
  eostutorial:
    container_name: eostutorial
    build: 
      context: .
      dockerfile: Dockerfile
    image: my/eostutorial
    ports:
      - '6666:6666'
      - '8000:8000'
      - '8080:8080'
    expose:
      - 6666