version: "3"

services:
  eostutorial:
    container_name: eostutorial
    build:
      context: ./services/eosio
      dockerfile: Dockerfile
    image: my/eostutorial
    ports:
      - '6666:6666' # keosd port
      - '8000:8000' # HTTP SERVER PORT
      - '8080:8080' # code server PORT
      - '9000:9000' # FIRST P2P PORT
    expose:
      - 6666
    volumes:
      - ./contracts:/opt/contracts   #container 內 mapping出來
      - ./services/eosio:/opt/application   #container 內 mapping出來
      - wallet-data-volume:/opt/eosio/bin/data-dir
volumes:
  wallet-data-volume:
    external: true
    #設True代表wallet-data-volume要存在 or error